export const MOVIE = {
  adult: false,
  backdrop_path: "/xHkOKPUe3ioXyPIe5odyL6o6cp4.jpg",
  created_by: [
    {
      id: 69414,
      credit_id: "5b341488c3a368531a019f53",
      name: "John Linson",
      gender: 2,
      profile_path: "/1rL4s8P5TS0KwbMbkwU7TvttIDy.jpg",
    },
    {
      id: 1215399,
      credit_id: "59a5dfe9c3a36840640129db",
      name: "Taylor Sheridan",
      gender: 2,
      profile_path: "/enrOQII7bCIf7U0WbdxiuXGfzrs.jpg",
    },
  ],
  episode_run_time: [42, 92, 60],
  first_air_date: "2018-06-20",
  genres: [
    {
      id: 37,
      name: "Western",
    },
    {
      id: 18,
      name: "Drama",
    },
  ],
  homepage: "http://www.paramountnetwork.com/shows/yellowstone",
  id: 73586,
  in_production: true,
  languages: ["en"],
  last_air_date: "2022-11-13",
  last_episode_to_air: {
    air_date: "2022-11-13",
    episode_number: 2,
    id: 3728945,
    name: "The Sting of Wisdom",
    overview:
      "As John makes a passionate speech to the state of Montana, a new formidable opponent from Market Equities arrives in Montana. The cowboys at the ranch deal with a new problem.",
    production_code: "",
    runtime: 60,
    season_number: 5,
    show_id: 73586,
    still_path: "/gAVvcD1NbX2iZJHHYWQNAF9Gucb.jpg",
    vote_average: 8,
    vote_count: 1,
  },
  name: "Yellowstone",
  next_episode_to_air: {
    air_date: "2022-11-20",
    episode_number: 3,
    id: 4033451,
    name: "Tall Drink of Water",
    overview:
      "Beth heads to Salt Lake City to take care of unfinished business; a trap is set for Jamie; Kayce makes an important decision for his family.",
    production_code: "",
    runtime: null,
    season_number: 5,
    show_id: 73586,
    still_path: null,
    vote_average: 0,
    vote_count: 0,
  },
  networks: [
    {
      id: 2076,
      name: "Paramount Network",
      logo_path: "/4knr4ozp2IQrA3SMQlLSYKcM3ML.png",
      origin_country: "US",
    },
  ],
  number_of_episodes: 45,
  number_of_seasons: 5,
  origin_country: ["US"],
  original_language: "en",
  original_name: "Yellowstone",
  overview:
    "Follow the violent world of the Dutton family, who controls the largest contiguous ranch in the United States. Led by their patriarch John Dutton, the family defends their property against constant attack by land developers, an Indian reservation, and America’s first National Park.",
  popularity: 793.324,
  poster_path: "/iqWCUwLcjkVgtpsDLs8xx8kscg6.jpg",
  production_companies: [
    {
      id: 4700,
      logo_path: "/A32wmjrs9Psf4zw0uaixF0GXfxq.png",
      name: "The Linson Company",
      origin_country: "US",
    },
    {
      id: 86985,
      logo_path: null,
      name: "Treehouse Films",
      origin_country: "US",
    },
    {
      id: 106789,
      logo_path: "/oEgUdRh5YWF6Il705WnpwauirIj.png",
      name: "Bosque Ranch Productions",
      origin_country: "US",
    },
    {
      id: 124254,
      logo_path: null,
      name: "101 Studios",
      origin_country: "US",
    },
  ],
  production_countries: [
    {
      iso_3166_1: "US",
      name: "United States of America",
    },
  ],
  seasons: [
    {
      air_date: "2018-06-20",
      episode_count: 9,
      id: 93559,
      name: "Season 1",
      overview: "",
      poster_path: "/vztZhTUNXk73mocDIXDd3nIfzRH.jpg",
      season_number: 1,
    },
    {
      air_date: "2019-06-19",
      episode_count: 10,
      id: 120916,
      name: "Season 2",
      overview: "",
      poster_path: "/3ePlESS6eyUj9W7yPEbzhwWaiFo.jpg",
      season_number: 2,
    },
    {
      air_date: "2020-06-21",
      episode_count: 10,
      id: 148960,
      name: "Season 3",
      overview: "",
      poster_path: "/43nVQqVsrshaOx9GfJq6JstsfCX.jpg",
      season_number: 3,
    },
    {
      air_date: "2021-11-07",
      episode_count: 10,
      id: 193949,
      name: "Season 4",
      overview: "",
      poster_path: "/iqWCUwLcjkVgtpsDLs8xx8kscg6.jpg",
      season_number: 4,
    },
    {
      air_date: "2022-11-13",
      episode_count: 6,
      id: 294246,
      name: "Season 5",
      overview: "",
      poster_path: "/peNC0eyc3TQJa6x4TdKcBPNP4t0.jpg",
      season_number: 5,
    },
  ],
  spoken_languages: [
    {
      english_name: "English",
      iso_639_1: "en",
      name: "English",
    },
  ],
  status: "Returning Series",
  tagline: "My land, my rules.",
  type: "Scripted",
  vote_average: 8.085,
  vote_count: 1217,
};
